sudo: required
services:
 - docker

before_install:
 - docker build -t sabhab/react-test -f ./client/Dockerfile.dev ./client

script;
 - docker run -e CI=true  sabhab/react-test npm test -- --coverage

after-sucess:
 - docker build -t sabhab/multi-client  ./client
 - docker build -t sabhab/multi-nginx ./nginx
 - docker build -t sabhab/multi-server ./server
 - docker build -t sabhab/multi-worker ./worker

 # Login into the Docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # Take those image and push to Docker hub
 - docker push sabhab/multi-client
 - docker push sabhab/multi-nginx
 - docker push sabhab/multi-server
 - docker push sabhab/multi-worker 




 
