sudo: required
language: generic 
services:
 - docker

before_install:
 - docker build -t sabhab1/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true  sabhab1/react-test npm test -- --coverage

after-sucess:
 - docker build -t sabhab1/multi-client  ./client
 - docker build -t sabhab1/multi-nginx ./nginx
 - docker build -t sabhab1/multi-server ./server
 - docker build -t sabhab1/multi-worker ./worker

 # Login into the Docker CLI

 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

 # Take those image and push to Docker hub
 - docker push sabhab1/multi-client
 - docker push sabhab1/multi-nginx
 - docker push sabhab1/multi-server
 - docker push sabhab1/multi-worker 

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker-app
  env: MultiDockerApp-env
  bucket_name: "elasticbeanstalk-us-west-2-892612947718"
  bucket_path: multi-docker-app
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRETE_KEY



 
