--- 
  services: 
    api: 
      build: 
        context: ./server
        dockerfile: Dockerfile.dev
      depends_on: 
        - postgres
      environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432
      volumes: 
        - /app/node_modules
        - "./server:/app"
    client: 
      build: 
        context: ./client
        dockerfile: Dockerfile.dev
      stdin_open: true
      volumes: 
        - /app/node_modules
        - "./client:/app"
    nginx: 
      build: 
        context: ./nginx
        dockerfile: Dockerfile.dev
      depends_on: 
        - api
        - client
      ports: 
        - "3050:80"
      restart: always
    postgres: 
      environment: 
        - POSTGRES_PASSWORD=postgres_password
      image: "postgres:latest"
    redis: 
      image: "redis:latest"
    worker: 
      build: 
        context: ./worker
        dockerfile: Dockerfile.dev
      environment: 
        - REDIS_HOST=redis
        - REDIS_PORT=6379
      volumes: 
        - /app/node_modules
        - "./worker:/app"
  version: "3"
  